
# Jekyll theme 
remote_theme: samarsault/plainwhite-jekyll

# Theme data
plainwhite:
  name: Izz Fauzi
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: samarsault
    github: ixxnafri
    linkedIn: in/izz-im-fauzi # format: locale/username
